//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lanpuda.Lims.UI.Assets.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lanpuda.Lims.UI.Assets.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 购置日期 的本地化字符串。
        /// </summary>
        public static string AcquisitionDate {
            get {
                return ResourceManager.GetString("AcquisitionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最终数量 的本地化字符串。
        /// </summary>
        public static string AfterQuantity {
            get {
                return ResourceManager.GetString("AfterQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本信息 的本地化字符串。
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 依据 的本地化字符串。
        /// </summary>
        public static string Basis {
            get {
                return ResourceManager.GetString("Basis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校准日期 的本地化字符串。
        /// </summary>
        public static string CalibrationDate {
            get {
                return ResourceManager.GetString("CalibrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校准结果 的本地化字符串。
        /// </summary>
        public static string CalibrationResult {
            get {
                return ResourceManager.GetString("CalibrationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校准标准 的本地化字符串。
        /// </summary>
        public static string CalibrationStandard {
            get {
                return ResourceManager.GetString("CalibrationStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 证书编号 的本地化字符串。
        /// </summary>
        public static string CertificateNumber {
            get {
                return ResourceManager.GetString("CertificateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认人 的本地化字符串。
        /// </summary>
        public static string ConfirmPerson {
            get {
                return ResourceManager.GetString("ConfirmPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人 的本地化字符串。
        /// </summary>
        public static string Consignee {
            get {
                return ResourceManager.GetString("Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人电话 的本地化字符串。
        /// </summary>
        public static string ConsigneeTel {
            get {
                return ResourceManager.GetString("ConsigneeTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 费用 的本地化字符串。
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户 的本地化字符串。
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户经理 的本地化字符串。
        /// </summary>
        public static string CustomerManager {
            get {
                return ResourceManager.GetString("CustomerManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认设备 的本地化字符串。
        /// </summary>
        public static string DefaultEquipment {
            get {
                return ResourceManager.GetString("DefaultEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门 的本地化字符串。
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样品属性 的本地化字符串。
        /// </summary>
        public static string DicSampleProperty {
            get {
                return ResourceManager.GetString("DicSampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示值 的本地化字符串。
        /// </summary>
        public static string DisplayValue {
            get {
                return ResourceManager.GetString("DisplayValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间 的本地化字符串。
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备 的本地化字符串。
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备类型 的本地化字符串。
        /// </summary>
        public static string EquipmentType {
            get {
                return ResourceManager.GetString("EquipmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过期日期 的本地化字符串。
        /// </summary>
        public static string ExpireTime {
            get {
                return ResourceManager.GetString("ExpireTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全称 的本地化字符串。
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否包含最大值 的本地化字符串。
        /// </summary>
        public static string HasMaxValue {
            get {
                return ResourceManager.GetString("HasMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否包含最小值 的本地化字符串。
        /// </summary>
        public static string HasMinValue {
            get {
                return ResourceManager.GetString("HasMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库数量 的本地化字符串。
        /// </summary>
        public static string InQuantity {
            get {
                return ResourceManager.GetString("InQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测日期 的本地化字符串。
        /// </summary>
        public static string InspectionDate {
            get {
                return ResourceManager.GetString("InspectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测项目 的本地化字符串。
        /// </summary>
        public static string InspectionItem {
            get {
                return ResourceManager.GetString("InspectionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测记录 的本地化字符串。
        /// </summary>
        public static string InspectionRecord {
            get {
                return ResourceManager.GetString("InspectionRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验任务 的本地化字符串。
        /// </summary>
        public static string InspectionTask {
            get {
                return ResourceManager.GetString("InspectionTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测人 的本地化字符串。
        /// </summary>
        public static string Inspector {
            get {
                return ResourceManager.GetString("Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装位置 的本地化字符串。
        /// </summary>
        public static string InstallationLocation {
            get {
                return ResourceManager.GetString("InstallationLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存 的本地化字符串。
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存流水 的本地化字符串。
        /// </summary>
        public static string InventoryLog {
            get {
                return ResourceManager.GetString("InventoryLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库业务 的本地化字符串。
        /// </summary>
        public static string InventoryOut {
            get {
                return ResourceManager.GetString("InventoryOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后修改时间 的本地化字符串。
        /// </summary>
        public static string LastModificationTime {
            get {
                return ResourceManager.GetString("LastModificationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后修改 的本地化字符串。
        /// </summary>
        public static string LastModifier {
            get {
                return ResourceManager.GetString("LastModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库位 的本地化字符串。
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生时间 的本地化字符串。
        /// </summary>
        public static string LogTime {
            get {
                return ResourceManager.GetString("LogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次号 的本地化字符串。
        /// </summary>
        public static string LotNumber {
            get {
                return ResourceManager.GetString("LotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维护周期 的本地化字符串。
        /// </summary>
        public static string MaintenancePeriod {
            get {
                return ResourceManager.GetString("MaintenancePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维护标准 的本地化字符串。
        /// </summary>
        public static string MaintenanceStandard {
            get {
                return ResourceManager.GetString("MaintenanceStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维护类型 的本地化字符串。
        /// </summary>
        public static string MaintenanceType {
            get {
                return ResourceManager.GetString("MaintenanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经理电话 的本地化字符串。
        /// </summary>
        public static string ManagerTel {
            get {
                return ResourceManager.GetString("ManagerTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制造商 的本地化字符串。
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大值 的本地化字符串。
        /// </summary>
        public static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小值 的本地化字符串。
        /// </summary>
        public static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下次校准日期 的本地化字符串。
        /// </summary>
        public static string NextCalibrationDate {
            get {
                return ResourceManager.GetString("NextCalibrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作手册 的本地化字符串。
        /// </summary>
        public static string OperationManual {
            get {
                return ResourceManager.GetString("OperationManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他信息 的本地化字符串。
        /// </summary>
        public static string OtherInformation {
            get {
                return ResourceManager.GetString("OtherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库数量 的本地化字符串。
        /// </summary>
        public static string OutQuantity {
            get {
                return ResourceManager.GetString("OutQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人员 的本地化字符串。
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优先级 的本地化字符串。
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品 的本地化字符串。
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品类型 的本地化字符串。
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目 的本地化字符串。
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 判级类型 的本地化字符串。
        /// </summary>
        public static string RatingType {
            get {
                return ResourceManager.GetString("RatingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原因 的本地化字符串。
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货信息 的本地化字符串。
        /// </summary>
        public static string ReceivingInformation {
            get {
                return ResourceManager.GetString("ReceivingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维修 的本地化字符串。
        /// </summary>
        public static string Repair {
            get {
                return ResourceManager.GetString("Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维修费用 的本地化字符串。
        /// </summary>
        public static string RepairCost {
            get {
                return ResourceManager.GetString("RepairCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维修日期 的本地化字符串。
        /// </summary>
        public static string RepairDate {
            get {
                return ResourceManager.GetString("RepairDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维修记录 的本地化字符串。
        /// </summary>
        public static string RepairRecord {
            get {
                return ResourceManager.GetString("RepairRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维修结果 的本地化字符串。
        /// </summary>
        public static string RepairResult {
            get {
                return ResourceManager.GetString("RepairResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维修耗时 的本地化字符串。
        /// </summary>
        public static string RepairTime {
            get {
                return ResourceManager.GetString("RepairTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结果 的本地化字符串。
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样品 的本地化字符串。
        /// </summary>
        public static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样品数量 的本地化字符串。
        /// </summary>
        public static string SampleCount {
            get {
                return ResourceManager.GetString("SampleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来样时间 的本地化字符串。
        /// </summary>
        public static string SampleTime {
            get {
                return ResourceManager.GetString("SampleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来样时间截止 的本地化字符串。
        /// </summary>
        public static string SampleTimeEnd {
            get {
                return ResourceManager.GetString("SampleTimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来样时间起始 的本地化字符串。
        /// </summary>
        public static string SampleTimeStart {
            get {
                return ResourceManager.GetString("SampleTimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样品类型 的本地化字符串。
        /// </summary>
        public static string SampleType {
            get {
                return ResourceManager.GetString("SampleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送样人 的本地化字符串。
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简称 的本地化字符串。
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规格 的本地化字符串。
        /// </summary>
        public static string Spec {
            get {
                return ResourceManager.GetString("Spec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 耗时 的本地化字符串。
        /// </summary>
        public static string SpentTime {
            get {
                return ResourceManager.GetString("SpentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准 的本地化字符串。
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准类型 的本地化字符串。
        /// </summary>
        public static string StandardType {
            get {
                return ResourceManager.GetString("StandardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商 的本地化字符串。
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采购经理 的本地化字符串。
        /// </summary>
        public static string SupplierManager {
            get {
                return ResourceManager.GetString("SupplierManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位 的本地化字符串。
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用记录 的本地化字符串。
        /// </summary>
        public static string UsageHistory {
            get {
                return ResourceManager.GetString("UsageHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用记录类型 的本地化字符串。
        /// </summary>
        public static string UsageHistoryType {
            get {
                return ResourceManager.GetString("UsageHistoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单编号 的本地化字符串。
        /// </summary>
        public static string WorkOrderNumber {
            get {
                return ResourceManager.GetString("WorkOrderNumber", resourceCulture);
            }
        }
    }
}
